version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.Date.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: 9fr4dl0CEVObeDqWLwrNLl6B7VYA+CdALCu1/hRwhsryP05QXsMJTptUibBrkMcQ
  artifact: /.*\.nupkg/
